pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot
      - status-success=build (12.x)
    actions:
      merge:
        method: merge
